name: Fetch-AWS-Secrets

on:
  workflow_dispatch:

jobs:
  fetch-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step to configure AWS credentials using web identity
    - name: Configure AWS Credentials using Web Identity
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::752354625103:role/vais-test
        aws-region: eu-west-1
        role-session-name: github-actions-session

    # Step to install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli jq

    # Step to retrieve credentials from AWS Secrets Manager
    - name: Fetch User Credentials from AWS Secrets Manager
      id: fetch-credentials
      run: |
        SECRET=$(aws secretsmanager get-secret-value --secret-id vais-test-secret --query SecretString --output text)
        echo "Retrieved Secret: $SECRET"
        echo "::set-output name=credentials::$SECRET"

    # Step to print the fetched credentials
    - name: Print Fetched Credentials
      run: |
        echo "User credentials: ${{ steps.fetch-credentials.outputs.credentials }}"
